### ISSUE TITLE
Disable split bill

### ISSUE THREAD

**Issue by ali28729** [brettmeyer/zapper-php-test#2]
Thanks a lot for this. In the zapper_test script even if i set split_bill to false, i still get an option to edit my invoice amount in the mobile app. Is this the correct way to achieve that or am i missing something.
Also if possible can you guide me to any relevant documentation available publicly since developer sign up for zapper is not currently functional.
Thanks in advance!

**Comment by brettmeyer** [comment]
Sorry for late reply, this has been fixed by updating

```
$questions[] = array(
                     'QuestionId' => 34,
                     'GroupId' => 7,
                     'Answer' => $bill_amount,
                     'Required' => true,
                     'Type' => 3
```

to:

```
$questions[] = array(
                     'QuestionId' => 34,
                     'GroupId' => 7,
                     'Answer' => $bill_amount,
                     'Required' => true,
                     'Type' => 11
```
